PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS users (
    id INTEGER NOT NULL PRIMARY KEY,
    salt VARCHAR(12) NOT NULL,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS users_id ON users(id);
CREATE UNIQUE INDEX IF NOT EXISTS users_email ON users(email);

CREATE TABLE IF NOT EXISTS posts (
    id INTEGER NOT NULL PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
    tags VARCHAR(255) NOT NULL,
    category VARCHAR(30) NOT NULL,
    published VARCHAR(30) NOT NULL,
    omment INTEGER NOT NULL,
    cover VARCHAR(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS posts_id ON posts(id);
CREATE UNIQUE INDEX IF NOT EXISTS posts_slug ON posts(slug);

CREATE TABLE IF NOT EXISTS tags (
    id INTEGER NOT NULL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    post_id INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS tags_name ON tags(name);
CREATE UNIQUE INDEX IF NOT EXISTS tags_id ON tags(id);

COMMIT;
